# Site settings
title: Tasty software
email: einar@codelette.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Einar Jónsson. I am a software developer based in Reykjavik, Iceland. To find out more about me see the About page.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: einarj
github_username:  einarj

# Build settings
markdown: kramdown
